snd-soc-aop-y		:= aop_audio.o
obj-$(CONFIG_SND_SOC_APPLE_AOP_AUDIO)	+= snd-soc-aop.o

snd-soc-apple-mca-y	:= mca.o

obj-$(CONFIG_SND_SOC_APPLE_MCA)	+= snd-soc-apple-mca.o

snd-soc-macaudio-objs	:= macaudio.o

obj-$(CONFIG_SND_SOC_APPLE_MACAUDIO)	+= snd-soc-macaudio.o
