# SPDX-License-Identifier: GPL-2.0 OR BSD-2-Clause

obj-$(CONFIG_PHY_APPLE_ATC)		+= phy-apple-atc.o
phy-apple-atc-y			:= atc.o

obj-$(CONFIG_PHY_APPLE_DPTX)	+= phy-apple-dptx.o
phy-apple-dptx-y		+= dptx.o
